/** v1.2 same-origin facade. Legacy method names remain; old score-submission
 * endpoints deliberately reject browser-provided scores. New learning UI uses api12. */
import type {Health,OnboardingBody,PlacementStart,PlacementResult,QuizSet,ProgramResult,Milestone,SkillLevel,Tips,WritingEval,SpeakingEval,Transcript,AttemptSummary,AttemptDetail,Trends,Lesson,LessonToday,MockScore,PronounceTarget,PronounceFeedback,VocabSet,Flashcard,CardStats,AccountUser,AccountSession,AdminUser,AdminStats,AdminAuditEntry,JobStatus} from "../types";
import {transport} from "../transport";
const BASE=(import.meta as {env?:{VITE_API_BASE?:string}}).env?.VITE_API_BASE??"";
export class ApiError extends Error{code:string;details:unknown;constructor(code:string,message:string,details?:unknown){super(message);this.name="ApiError";this.code=code;this.details=details;}}
const request=<T>(p:string,opts:RequestInit={})=>transport<T>(BASE,p,opts,ApiError);
const post=<T>(p:string,b:unknown)=>request<T>(p,{method:"POST",body:JSON.stringify(b??{})});
const get=<T>(p:string)=>request<T>(p);
export type GateStatus={activeSeconds:number;thresholdSeconds:number;heartbeatSec:number;locked:boolean;unlocked:boolean;isAdmin:boolean};
export const api={
 health:()=>get<Health>("/api/health"),
 historyReadiness:()=>get<unknown>("/api/history/readiness"),
 authStatus:()=>get<{authRequired:boolean;authenticated:boolean}>("/api/auth/status"),
 accountMe:()=>get<AccountUser>("/api/account/me"),
 accountExport:()=>get<Record<string,unknown>>("/api/account/export"),
 accountSessions:()=>get<AccountSession[]>("/api/account/sessions"),
 adminUsers:()=>get<AdminUser[]>("/api/admin/users"),
 adminStats:()=>get<AdminStats>("/api/admin/stats"),
 adminAudit:()=>get<AdminAuditEntry[]>("/api/admin/audit"),
 milestones:()=>get<Milestone[]>("/api/program/milestones"),
 skillLevels:()=>get<SkillLevel[]>("/api/skill-levels"),
 statsTrends:()=>get<Trends>("/api/stats/trends"),
 statsActivity:()=>get<{current:number;longest:number;today:number;daysActive:number}>("/api/stats/activity"),
 lessonToday:()=>get<LessonToday>("/api/lesson/today"),
 mocksList:()=>get<MockScore[]>("/api/mocks"),
 cardsList:()=>get<{cards:Flashcard[];stats:CardStats}>("/api/cards"),
 cardsDue:()=>get<Flashcard[]>("/api/cards/due"),
 gateStatus:()=>get<GateStatus>("/api/gate/status"),
 authLogout:()=>post<{ok:boolean}>("/api/auth/logout",{}),
 accountLogout:()=>post<{ok:boolean}>("/api/account/logout",{}),
 accountVerifyResend:()=>post<{ok:boolean}>("/api/account/verify/resend",{}),
 accountRegister:(b:{email:string;password:string})=>post<AccountUser>("/api/account/register",b),
 accountLogin:(b:{email:string;password:string;remember?:boolean;totp?:string})=>post<AccountUser>("/api/account/login",b),
 accountPassword:(b:{currentPassword:string;newPassword:string})=>post<{ok:boolean}>("/api/account/password",b),
 accountReset:(b:{token:string;newPassword:string})=>post<{ok:boolean}>("/api/account/reset",b),
 adminReauth:(b:{password:string;totp?:string})=>post<{ok:boolean}>("/api/admin/reauth",b),
 onboarding:(b:OnboardingBody)=>post<unknown>("/api/onboarding",b),
 placementSubmit:(b:unknown)=>post<PlacementResult>("/api/placement/submit",b),
 practiceAttempt:(b:{skill:string;band:number;correct:number;total:number})=>post<{savedId:number}>("/api/practice/attempt",b),
 milestoneAdd:(b:{title:string;dayTarget:number;targets:Record<string,string>})=>post<{id:number}>("/api/program/milestones",b),
 writingEvaluate:(b:unknown)=>post<WritingEval>("/api/writing/evaluate",b),
 speakingEvaluate:(b:unknown)=>post<SpeakingEval>("/api/speaking/evaluate",b),
 speakingRoleplay:(b:{scenario:string;history:{role:string;text:string}[];userText:string})=>post<{reply:string}>("/api/speaking/roleplay",b),
 lessonGenerate:(b:{day?:number;focus?:string;band?:string;force?:boolean})=>post<LessonToday>("/api/lesson/generate",b),
 mockSave:(b:{listening:number;reading:number;overall:number})=>post<{id:number}>("/api/mocks",b),
 pronounceSentence:(b:{level?:string;topic?:string})=>post<PronounceTarget>("/api/pronounce/sentence",b),
 vocab:(b:{topic:string;level?:string})=>post<VocabSet>("/api/vocab",b),
 cardAdd:(b:{front:string;back:string}|{cards:{front:string;back:string}[]})=>post<{id?:number;added?:number}>("/api/cards",b),
 authLogin:(passcode:string)=>post<{ok:boolean}>("/api/auth/login",{passcode}),
 accountGoogle:(credential:string,totp?:string)=>post<AccountUser>("/api/account/google",{credential,totp}),
 accountProfile:(b:{name?:string;country?:string;examDate?:string;bio?:string;targetBand?:number;skillTargets?:Record<string,string|number>;reminderTime?:string|null;reminderTz?:string|null})=>request<AccountUser>("/api/account/profile",{method:"PATCH",body:JSON.stringify(b)}),
 accountAvatar:(dataUrl:string)=>post<{ok:boolean}>("/api/account/avatar",{dataUrl}),
 accountDelete:()=>request<{ok:boolean}>("/api/account",{method:"DELETE"}),
 accountForgot:(email:string)=>post<{ok:boolean}>("/api/account/forgot",{email}),
 accountVerify:(token:string)=>post<{ok:boolean}>("/api/account/verify",{token}),
 accountRevokeOtherSessions:()=>request<{revoked:number}>("/api/account/sessions/others",{method:"DELETE"}),
 accountRevokeAllSessions:()=>request<{revoked:number}>("/api/account/sessions",{method:"DELETE"}),
 adminDeleteUser:(id:number)=>request<{ok:boolean}>(`/api/admin/users/${id}`,{method:"DELETE"}),
 adminResetUser:(id:number)=>post<{ok:boolean}>(`/api/admin/users/${id}/reset-password`,{}),
 placementStart:()=>post<PlacementStart>("/api/placement/start",{}),
 practiceGenerate:()=>post<{jobId:string}>("/api/practice/generate",{}),
 practiceStatus:(jobId:string)=>get<{done:boolean;progress:number}>(`/api/practice/status?jobId=${encodeURIComponent(jobId)}`),
 practiceSet:(skill:string,band?:string)=>get<QuizSet>(`/api/practice/set?skill=${encodeURIComponent(skill)}${band?`&band=${encodeURIComponent(band)}`:""}`),
 program:(lengthDays:number)=>post<ProgramResult>("/api/program",{lengthDays}),
 milestoneUpdate:(id:number,b:{title?:string;dayTarget?:number;targets?:Record<string,string>})=>request<Milestone>(`/api/program/milestones/${id}`,{method:"PUT",body:JSON.stringify(b)}),
 milestoneDelete:(id:number)=>request<{deleted:number}>(`/api/program/milestones/${id}`,{method:"DELETE"}),
 tips:(skill:string)=>get<Tips>(`/api/tips/${encodeURIComponent(skill)}`),
 speakingTranscribe:(audio:Blob)=>{const form=new FormData();form.append("audio",audio,"speech.webm");return request<Transcript>("/api/speaking/transcribe",{method:"POST",body:form});},
 jobStatus:(id:string)=>get<JobStatus>(`/api/jobs/${encodeURIComponent(id)}`),
 readingGenerate:(band:string)=>post<QuizSet>("/api/reading/generate",{band}),
 listeningGenerate:(band:string)=>post<QuizSet>("/api/listening/generate",{band}),
 historyAttempts:(type?:"writing"|"speaking")=>get<AttemptSummary[]>(`/api/history/attempts${type?`?type=${type}`:""}`),
 historyAttempt:(id:number)=>get<AttemptDetail>(`/api/history/attempt/${id}`),
 lesson:(day:number)=>get<{day:number;focus?:string;lesson:Lesson|null}>(`/api/lesson/${day}`),
 pronounceFeedback:(b:{target:string;transcript:string;accuracy:number;missed:string[]})=>post<PronounceFeedback>("/api/pronounce/feedback",{target:b.target,transcript:b.transcript}),
 cardReview:(id:number,quality:number)=>post<Flashcard>(`/api/cards/${id}/review`,{quality}),
 cardDelete:(id:number)=>request<{deleted:number}>(`/api/cards/${id}`,{method:"DELETE"}),
 gateHeartbeat:(seconds:number)=>post<{activeSeconds:number;locked:boolean;unlocked:boolean}>("/api/gate/heartbeat",{seconds}),
 gateUnlock:(stars:number,insight:string)=>post<{unlocked:boolean}>("/api/gate/unlock",{stars,insight}),
};
