import {useState} from "react";
import type {Evaluation} from "./api";
import {Panel,Notice,Tabs,text,type Locale} from "./shared";
const LABELS:Record<string,[string,string]>={taskResponse:["Task response","Respons tugas"],taskAchievement:["Task achievement","Pemenuhan tugas"],coherenceCohesion:["Coherence & cohesion","Koherensi & kohesi"],lexicalResource:["Lexical resource","Kosakata"],grammaticalRange:["Grammar range & accuracy","Rentang & ketepatan tata bahasa"],fluencyCoherence:["Text coherence estimate","Estimasi koherensi teks"],pronunciation:["Pronunciation","Pelafalan"]};
export function Feedback({result,lang}:{result:Evaluation;lang:Locale}){
 const [tab,setTab]=useState("feedback");const overall=result.bands?.overall;
 return <div className="learn-stack"><section className="learn-result-summary"><div><span className="learn-eyebrow">{result.stub?text(lang,"DEMO RESPONSE · NOT AN ASSESSMENT","RESPONS DEMO · BUKAN PENILAIAN"):text(lang,"PRACTICE ESTIMATE","ESTIMASI LATIHAN")}</span><h2>{text(lang,"Keep the idea. Refine the expression.","Pertahankan ide. Perbaiki penyampaiannya.")}</h2><p>{result.savedId?text(lang,"Your response and feedback have been saved.","Respons dan umpan balikmu telah disimpan."):text(lang,"Saving has not been confirmed.","Penyimpanan belum terkonfirmasi.")}</p></div><div className="learn-accuracy"><strong>{result.stub?"—":typeof overall==="number"?overall.toFixed(1):"—"}</strong><span>{text(lang,"Estimated band","Estimasi band")}</span></div></section><Notice>{result.stub?text(lang,"This server is in stub mode. The feedback below is a fixed example and does not assess your response.","Server dalam mode stub. Umpan balik di bawah merupakan contoh tetap dan tidak menilai responsmu."):text(lang,"AI practice guidance, not an official IELTS score. Speaking text cannot establish pronunciation or acoustic fluency.","Panduan latihan AI, bukan skor IELTS resmi. Teks speaking tidak dapat menentukan pelafalan atau kelancaran akustik.")}</Notice><div className="learn-criteria">{Object.entries(result.bands||{}).filter(([k])=>k!=="overall").map(([k,v])=><Panel key={k}><h3>{LABELS[k]?text(lang,...LABELS[k]):k}</h3><strong>{result.stub?"—":typeof v==="number"?v.toFixed(1):text(lang,"Not assessed","Belum dinilai")}</strong><span>{typeof v==="number"?text(lang,"Practice estimate","Estimasi latihan"):text(lang,"Audio evidence required","Memerlukan bukti audio")}</span></Panel>)}</div><Tabs label="Feedback sections" value={tab} onChange={setTab} items={[{id:"feedback",label:text(lang,"Feedback","Umpan balik")},...(result.rewrite?[{id:"rewrite",label:text(lang,"Suggested revision","Saran revisi")}]:[]),...(result.modelAnswer?[{id:"model",label:text(lang,"Example answer","Contoh jawaban")}]:[])]}/>
 {tab==="feedback"&&<>{result.feedback&&<Panel title={text(lang,"Where to focus next","Fokus berikutnya")}><p className="learn-prose">{result.feedback}</p></Panel>}{!!result.corrections?.length&&<Panel title={text(lang,"Small edits, clearer meaning","Perbaikan kecil, makna lebih jelas")}><div className="learn-corrections">{result.corrections.map((c,i)=><article key={i}><span className="learn-step">{i+1}</span><div><div className="learn-correction-before"><span>{text(lang,"Original","Sebelum")}</span><p>{c.original}</p></div><div className="learn-correction-after"><span>{text(lang,"Suggested","Saran")}</span><p>{c.fixed}</p></div><p>{c.note}</p></div></article>)}</div></Panel>}{!!result.vocabUpgrades?.length&&<Panel title={text(lang,"More precise language","Bahasa yang lebih tepat")}><div className="learn-vocab-upgrades">{result.vocabUpgrades.map((v,i)=><div key={i}><span>{v.from}</span><b>→ {v.to}</b><p>{v.note}</p></div>)}</div></Panel>}</>}
 {tab!=="feedback"&&<Panel title={tab==="rewrite"?text(lang,"A revision to learn from","Revisi untuk dipelajari"):text(lang,"One possible answer","Salah satu contoh jawaban")}><p className="learn-fineprint">{text(lang,"Use this to study structure and choices, not as text to submit as your own.","Pelajari struktur dan pilihan katanya, bukan untuk dikirim sebagai tulisanmu sendiri.")}</p><p className="learn-prose">{tab==="rewrite"?result.rewrite:result.modelAnswer}</p></Panel>}</div>;
}
