import {useRef,useState} from "react";
import {request,type CardData} from "./api";
import {Panel,Notice,Button,Dialog,LoadState,useLoad,text,type Locale} from "./shared";
export function AvatarEditor({lang,onUpdated}:{lang:Locale;onUpdated:(data:string)=>void}){
 const input=useRef<HTMLInputElement>(null),[busy,setBusy]=useState(false),[error,setError]=useState("");
 async function upload(file?:File){if(!file)return;setError("");if(!["image/png","image/jpeg"].includes(file.type)||file.size>2000000){setError(text(lang,"Choose a PNG or JPEG smaller than 2 MB.","Pilih PNG atau JPEG kurang dari 2 MB."));return;}setBusy(true);try{const data=await new Promise<string>((resolve,reject)=>{const reader=new FileReader();reader.onload=()=>resolve(String(reader.result));reader.onerror=()=>reject(new Error("Image could not be read"));reader.readAsDataURL(file);});await request("/api/account/avatar",{dataUrl:data});onUpdated(data);}catch(e){setError(e instanceof Error?e.message:"Image was not saved");}finally{setBusy(false);if(input.current)input.current.value="";}}
 return <div className="learn-stack"><input className="aru-sr-only" type="file" accept="image/png,image/jpeg" ref={input} onChange={e=>void upload(e.target.files?.[0])} aria-label={text(lang,"Choose profile image","Pilih foto profil")}/><div className="aru-actions"><Button secondary busy={busy} onClick={()=>input.current?.click()}>{text(lang,"Update profile photo","Perbarui foto profil")}</Button><span className="learn-fineprint">PNG / JPEG · 2 MB</span></div>{error&&<Notice tone="error">{error}</Notice>}</div>;
}
interface Checkpoint{id:number;idx:number;title:string;dayTarget:number;targets:Record<string,string>}
export function CheckpointsEditor({lang}:{lang:Locale}){
 const r=useLoad(()=>request<Checkpoint[]>("/api/program/milestones"),"checkpoints"),[edit,setEdit]=useState<Partial<Checkpoint>|null>(null),[remove,setRemove]=useState<Checkpoint|null>(null),[busy,setBusy]=useState(false),[error,setError]=useState("");
 async function save(){if(!edit)return;setBusy(true);setError("");try{const body={title:edit.title,dayTarget:edit.dayTarget,targets:edit.targets||{}};await request(edit.id?`/api/program/milestones/${edit.id}`:"/api/program/milestones",body,edit.id?"PUT":"POST");setEdit(null);r.retry();}catch(e){setError(e instanceof Error?e.message:"Checkpoint was not saved");}finally{setBusy(false);}}
 async function del(){if(!remove)return;setBusy(true);setError("");try{await request(`/api/program/milestones/${remove.id}`,undefined,"DELETE");setRemove(null);r.retry();}catch(e){setError(e instanceof Error?e.message:"Checkpoint was not deleted");}finally{setBusy(false);}}
 return <><Panel title={text(lang,"Planned checkpoints","Checkpoint terencana")}><p>{text(lang,"Edit your plan without marking it as achieved. Create a planning horizon first if you do not have a program.","Ubah rencana tanpa menandainya telah tercapai. Buat rentang perencanaan lebih dahulu bila belum memiliki program.")}</p><Button secondary onClick={()=>setEdit({title:"",dayTarget:15,targets:{}})}>{text(lang,"Add checkpoint","Tambah checkpoint")}</Button>{r.busy||r.error?<LoadState busy={r.busy} error={r.error} onRetry={r.retry} lang={lang}/>:!r.data?.length?<Notice>{text(lang,"No checkpoints yet. A program is required before adding one.","Belum ada checkpoint. Program diperlukan sebelum menambahkan checkpoint.")}</Notice>:r.data.map(m=><div className="learn-toolbar" key={m.id}><div><span className="learn-eyebrow">DAY {m.dayTarget}</span><h3>{m.title}</h3><p className="learn-fineprint">{Object.entries(m.targets).map(([s,t])=>`${s}: ${t}`).join(" · ")}</p></div><div className="aru-actions"><button className="aru-text-button" onClick={()=>setEdit({...m})}>{text(lang,"Edit","Ubah")}</button><button className="aru-text-button" onClick={()=>setRemove(m)}>{text(lang,"Delete","Hapus")}</button></div></div>)}</Panel>{error&&<Notice tone="error">{error}</Notice>}{edit&&<Dialog title={text(lang,"Edit planned checkpoint","Ubah checkpoint rencana")} onClose={()=>{if(!busy)setEdit(null);}}>{error&&<Notice tone="error">{error}</Notice>}<label className="learn-field"><span>{text(lang,"Title","Judul")}</span><input maxLength={200} value={edit.title||""} onChange={e=>setEdit(m=>({...m,title:e.target.value}))}/></label><label className="learn-field"><span>{text(lang,"Program day","Hari program")}</span><input type="number" min={1} max={365} value={edit.dayTarget||1} onChange={e=>setEdit(m=>({...m,dayTarget:Number(e.target.value)}))}/></label><div className="learn-form-grid">{["reading","listening","writing","speaking"].map(skill=><label className="learn-field" key={skill}><span>{skill}</span><select value={edit.targets?.[skill]||""} onChange={e=>setEdit(m=>{const targets={...m?.targets};if(e.target.value)targets[skill]=e.target.value;else delete targets[skill];return {...m,targets};})}><option value="">—</option>{["A1A2","B1","B2","C1","C2"].map(level=><option key={level}>{level}</option>)}</select></label>)}</div><div className="aru-actions"><Button busy={busy} disabled={!edit.title?.trim()} onClick={()=>void save()}>{text(lang,"Save checkpoint","Simpan checkpoint")}</Button></div></Dialog>}{remove&&<Dialog title={text(lang,"Delete this planned checkpoint?","Hapus checkpoint rencana ini?")} onClose={()=>{if(!busy)setRemove(null);}}>{error&&<Notice tone="error">{error}</Notice>}<p>{remove.title}</p><div className="aru-actions"><Button secondary onClick={()=>setRemove(null)}>{text(lang,"Cancel","Batal")}</Button><Button busy={busy} onClick={()=>void del()}>{text(lang,"Delete checkpoint","Hapus checkpoint")}</Button></div></Dialog>}</>;
}
export function CardCollection({lang}:{lang:Locale}){
 const r=useLoad(()=>request<{cards:CardData[];stats:{total:number;due:number}}>("/api/cards"),"collection"),[remove,setRemove]=useState<CardData|null>(null),[busy,setBusy]=useState(false),[error,setError]=useState("");
 async function del(){if(!remove)return;setBusy(true);setError("");try{await request(`/api/cards/${remove.id}`,undefined,"DELETE");r.setData(old=>old?{...old,cards:old.cards.filter(c=>c.id!==remove.id)}:old);setRemove(null);}catch(e){setError(e instanceof Error?e.message:"Card was not deleted");}finally{setBusy(false);}}
 return <><Panel title={text(lang,"Your flashcard collection","Koleksi kartu belajarmu")}>{r.busy||r.error?<LoadState busy={r.busy} error={r.error} onRetry={r.retry} lang={lang}/>:!r.data?.cards.length?<p>{text(lang,"Your collection is empty.","Koleksimu masih kosong.")}</p>:r.data.cards.map(c=><div className="learn-toolbar" key={c.id}><div><h3>{c.front}</h3><p className="learn-fineprint">{c.back}</p></div><button className="aru-text-button" onClick={()=>setRemove(c)}>{text(lang,"Delete card","Hapus kartu")}</button></div>)}</Panel>{error&&<Notice tone="error">{error}</Notice>}{remove&&<Dialog title={text(lang,"Delete this flashcard?","Hapus kartu belajar ini?")} onClose={()=>{if(!busy)setRemove(null);}}>{error&&<Notice tone="error">{error}</Notice>}<p>{remove.front}</p><div className="aru-actions"><Button secondary onClick={()=>setRemove(null)}>{text(lang,"Cancel","Batal")}</Button><Button busy={busy} onClick={()=>void del()}>{text(lang,"Delete","Hapus")}</Button></div></Dialog>}</>;
}
