import {useEffect,useRef,useState} from "react";
import {api12,type Practice,type PracticeResult,type Skill} from "./api";
import {Heading,Panel,Notice,Button,Dialog,useUnsaved,text,type Locale,type Nav} from "./shared";
import {Icon} from "../views";
import {Timer} from "../../components/ui/Timer";
export function QuestionForm({task,answers,onAnswer,disabled=false,lang="en"}:{lang?:Locale;task:Practice;answers:string[];onAnswer:(i:number,v:string)=>void;disabled?:boolean}){
 return <div className="learn-questions">{task.questions.map((q,i)=><fieldset key={i} id={`question-${i}`} disabled={disabled} className="learn-question"><legend><span>{String(i+1).padStart(2,"0")}</span>{q.stem}</legend>{q.options?.length?<div className="learn-options">{q.options.map((o,j)=><label key={o} className={answers[i]===o?"selected":""}><input type="radio" name={`q-${task.practiceId}-${i}`} checked={answers[i]===o} onChange={()=>onAnswer(i,o)}/><span className="learn-option-letter">{String.fromCharCode(65+j)}</span><span>{o}</span></label>)}</div>:<input className="learn-input" maxLength={300} value={answers[i]||""} onChange={e=>onAnswer(i,e.target.value)} aria-label={`${text(lang,"Answer","Jawaban")} ${i+1}`} placeholder={text(lang,"Your answer","Jawabanmu")}/>}</fieldset>)}</div>;
}
function ListeningPlayer({transcript,lang}:{transcript:string;lang:Locale}){
 const [playing,setPlaying]=useState(false),[error,setError]=useState("");
 useEffect(()=>()=>window.speechSynthesis?.cancel(),[]);
 function play(){if(!window.speechSynthesis){setError(text(lang,"Speech playback is unavailable in this browser.","Pemutaran suara tidak tersedia di browser ini."));return;}
  window.speechSynthesis.cancel();const utterance=new SpeechSynthesisUtterance(transcript);utterance.lang="en-GB";utterance.rate=.95;utterance.onend=()=>setPlaying(false);utterance.onerror=()=>{setPlaying(false);setError(text(lang,"Audio could not be played. Try again.","Audio tidak dapat diputar. Coba lagi."));};setPlaying(true);window.speechSynthesis.speak(utterance);}
 return <Panel title={text(lang,"Listen with intention","Simak dengan saksama")}><div className="learn-player"><span className="learn-icon learn-listening"><Icon name="listening" size={28}/></span><div><b>{text(lang,"Practice audio","Audio latihan")}</b><p>{text(lang,"Browser-generated speech · replay allowed","Suara dari browser · boleh diputar ulang")}</p></div><Button secondary onClick={()=>{if(playing){window.speechSynthesis.cancel();setPlaying(false);}else play();}}>{playing?text(lang,"Stop","Hentikan"):text(lang,"Play","Putar")}</Button></div><p className="learn-fineprint">{text(lang,"This uses your browser's speech service, which may require a connection. It is not official test audio.","Menggunakan layanan suara browser yang mungkin memerlukan koneksi. Ini bukan audio tes resmi.")}</p>{error&&<Notice tone="error">{error}</Notice>}</Panel>;
}
export function ResultPanel({result,lang,onNext}:{result:PracticeResult;lang:Locale;onNext?:()=>void}){return <><section className="learn-result-summary"><div><span className="learn-eyebrow">{text(lang,"SAVED · SERVER-CHECKED","TERSIMPAN · DIPERIKSA SERVER")}</span><h2>{text(lang,"A clearer picture of this practice.","Gambaran latihan yang lebih jelas.")}</h2><p>{text(lang,"Review the reasoning, not just the number.","Pahami alasannya, bukan hanya angkanya.")}</p></div><div className="learn-accuracy"><strong>{result.accuracyPct}%</strong><span>{result.correct} / {result.total} {text(lang,"correct","benar")}</span></div></section><Notice>{text(lang,"This is short-practice accuracy, not an IELTS band or a readiness probability.","Ini akurasi latihan singkat, bukan band IELTS atau probabilitas kesiapan.")}</Notice><Panel title={text(lang,"Your answer review","Tinjauan jawabanmu")}><div className="learn-answer-review">{result.review.map(q=><article key={q.index} className={q.correct?"correct":"incorrect"}><div className="learn-review-number">{q.index+1}<Icon name={q.correct?"check":"close"} size={14}/></div><div><h3>{q.stem}</h3><dl><div><dt>{text(lang,"Your answer","Jawabanmu")}</dt><dd>{q.submitted||text(lang,"Unanswered","Belum dijawab")}</dd></div>{!q.correct&&<div><dt>{text(lang,"Expected answer","Jawaban yang diharapkan")}</dt><dd>{q.expected}</dd></div>}</dl>{q.explanation&&<p>{q.explanation}</p>}</div></article>)}</div></Panel>{onNext&&<Button onClick={onNext}>{text(lang,"Try another practice","Coba latihan lain")}<Icon name="arrow" size={17}/></Button>}</>;}
export function PracticeScreen({skill,lang,nav,timed=false}:{skill:Skill;lang:Locale;nav:Nav;timed?:boolean}){
 const [task,setTask]=useState<Practice|null>(null),[answers,setAnswers]=useState<string[]>([]),[result,setResult]=useState<PracticeResult|null>(null),[busy,setBusy]=useState(false),[error,setError]=useState(""),[confirm,setConfirm]=useState(false),[level,setLevel]=useState("B1"),[frozen,setFrozen]=useState(false);
 const latch=useRef(false),taskRef=useRef<Practice|null>(null);taskRef.current=task;
 useUnsaved(!!task&&!result,lang);
 useEffect(()=>()=>{window.speechSynthesis?.cancel();const t=taskRef.current;if(t)void api12.close(t.practiceId).catch(()=>{});},[]);
 async function start(){if(latch.current)return;latch.current=true;setBusy(true);setError("");try{if(task)await api12.close(task.practiceId);const t=await api12.start(skill,level);if(!t.practiceId||!Array.isArray(t.questions)||!t.questions.length)throw new Error("Invalid practice response");setTask(t);setAnswers(t.questions.map(()=>""));setResult(null);setFrozen(false);}catch(e){setError(e instanceof Error?e.message:"Practice unavailable");}finally{latch.current=false;setBusy(false);}}
 async function submit(){if(!task||latch.current||result)return;latch.current=true;setFrozen(true);setConfirm(false);setBusy(true);setError("");try{const r=await api12.submit(task.practiceId,answers);if(!Number.isInteger(r.savedId)||!Array.isArray(r.review))throw new Error("Invalid saved-result response");setResult(r);window.speechSynthesis?.cancel();}catch(e){setError(e instanceof Error?e.message:"Submission not confirmed");}finally{latch.current=false;setBusy(false);}}
 const title=skill==="reading"?text(lang,"Reading practice","Latihan membaca"):text(lang,"Listening practice","Latihan menyimak");
 return <div className="learn-page"><Heading title={title} description={text(lang,"Take your time. Build understanding one answer at a time.","Luangkan waktu. Bangun pemahaman dari setiap jawaban.")} icon={skill} tag={text(lang,"Accuracy, not IELTS bands","Akurasi, bukan band IELTS")} lang={lang} nav={nav}/>{error&&<Notice tone="error"><b>{frozen?text(lang,"Saving is not confirmed.","Penyimpanan belum terkonfirmasi."):text(lang,"Practice unavailable.","Latihan belum tersedia.")}</b><p>{error}</p>{frozen&&<><p>{text(lang,"Your answers are locked for a safe retry. The server will not create a duplicate result.","Jawaban dikunci untuk pengiriman ulang yang aman. Server tidak membuat hasil duplikat.")}</p><Button onClick={()=>void submit()} busy={busy}>{text(lang,"Retry the same submission","Kirim ulang jawaban yang sama")}</Button></>}</Notice>}
 {!task?<Panel><div className="learn-intro"><div className={`learn-hero-icon learn-${skill}`}><Icon name={skill} size={44}/></div><span className="learn-eyebrow">{text(lang,"ONE FOCUSED SESSION","SATU SESI TERARAH")}</span><h2>{text(lang,"Understand. Answer. Reflect.","Pahami. Jawab. Tinjau.")}</h2><p>{text(lang,"A validated task from the practice pool. Your answers are checked on the server and saved only after submission.","Soal tervalidasi dari pustaka latihan. Jawaban diperiksa server dan disimpan setelah dikirim.")}</p><label className="learn-field"><span>{text(lang,"Practice difficulty","Tingkat kesulitan")}</span><select value={level} onChange={e=>setLevel(e.target.value)}>{["A1A2","B1","B2","C1","C2"].map(l=><option key={l}>{l}</option>)}</select></label><Button onClick={()=>void start()} busy={busy}>{text(lang,"Start practice","Mulai latihan")}<Icon name="arrow" size={18}/></Button><small>{text(lang,"The selected task comes from the pool; replenishment may run in the background.","Soal dipilih dari pustaka; pengisian pustaka dapat berjalan di latar belakang.")}</small></div></Panel>:result?<ResultPanel result={result} lang={lang} onNext={()=>void start()}/>:<><div className="learn-toolbar"><div><span className="learn-tag">{task.difficulty}</span><strong>{task.title}</strong></div><span>{answers.filter(a=>a.trim()).length} / {answers.length} {text(lang,"answered","terjawab")}</span>{timed&&<Timer seconds={1800} resetKey={task.practiceId} onExpire={()=>void submit()}/>}</div>{task.repeat&&<Notice>{text(lang,"You may have seen this task before. Available pool content is limited.","Kamu mungkin pernah melihat soal ini. Isi pustaka yang tersedia masih terbatas.")}</Notice>}{skill==="listening"&&<ListeningPlayer transcript={task.transcript} lang={lang}/>}<div className={skill==="reading"?"learn-two-pane":""}>{skill==="reading"&&<Panel title={task.title} className="learn-reading-passage"><span className="learn-eyebrow">{text(lang,"READING PASSAGE","TEKS BACAAN")}</span><div>{task.passage.split(/\n+/).map((p,i)=><p key={i}>{p}</p>)}</div></Panel>}<Panel><QuestionForm lang={lang} task={task} answers={answers} disabled={busy||frozen} onAnswer={(i,v)=>setAnswers(a=>a.map((old,j)=>j===i?v:old))}/><div className="learn-submit"><p>{text(lang,"Answers stay editable until you submit. No band score will be inferred.","Jawaban dapat diubah sebelum dikirim. Tidak ada band yang ditebak.")}</p><Button busy={busy} disabled={frozen} onClick={()=>{if(answers.some(a=>!a.trim()))setConfirm(true);else void submit();}}>{text(lang,"Submit & save","Kirim & simpan")}<Icon name="check" size={18}/></Button></div></Panel></div></>}
 {confirm&&<Dialog title={text(lang,"Some answers are still empty","Sebagian jawaban masih kosong")} onClose={()=>setConfirm(false)}><p>{text(lang,"Unanswered questions will count as incorrect. Submit anyway?","Soal yang belum dijawab dihitung salah. Tetap kirim?")}</p><div className="aru-actions"><Button secondary onClick={()=>setConfirm(false)}>{text(lang,"Keep working","Lanjut mengerjakan")}</Button><Button onClick={()=>void submit()}>{text(lang,"Submit answers","Kirim jawaban")}</Button></div></Dialog>}</div>;
}
