import {useEffect,useState} from "react";
import {request} from "./api";
import {Recorder} from "./Recorder";
import {Heading,Panel,Notice,Button,text,type Locale,type Nav} from "./shared";
import {Icon} from "../views";
export function PronounceScreen({lang,nav}:{lang:Locale;nav:Nav}){
 const [target,setTarget]=useState("The early train to the city usually arrives before eight in the morning."),[transcript,setTranscript]=useState(""),[busy,setBusy]=useState(false),[error,setError]=useState(""),[feedback,setFeedback]=useState<{summary:string;wordTips:{word:string;tip:string}[];prosody:string[];stub?:boolean}|null>(null);
 useEffect(()=>()=>window.speechSynthesis?.cancel(),[]);
 async function sentence(){window.speechSynthesis?.cancel();setBusy(true);setError("");try{const r=await request<{text:string}>("/api/pronounce/sentence",{level:"B1"});if(!r.text)throw new Error("No sentence returned");setTarget(r.text);setFeedback(null);setTranscript("");}catch(e){setError(e instanceof Error?e.message:"Sentence unavailable");}finally{setBusy(false);}}
 async function review(){setBusy(true);setError("");try{setFeedback(await request("/api/pronounce/feedback",{target,transcript}));}catch(e){setError(e instanceof Error?e.message:"Feedback unavailable");}finally{setBusy(false);}}
 return <div className="learn-page"><Heading title={text(lang,"Read aloud, reflect clearly","Baca lantang, tinjau dengan jelas")} description={text(lang,"Use transcription as a word-recognition aid—not a pronunciation score.","Gunakan transkripsi untuk membantu pengenalan kata, bukan sebagai skor pelafalan.")} icon="speaking" tag="READ-ALOUD PRACTICE" nav={nav} lang={lang}/><Notice>{text(lang,"Recognized words are imperfect evidence. No phoneme accuracy, pronunciation band, or acoustic fluency is inferred.","Kata yang dikenali merupakan bukti yang tidak sempurna. Tidak ada akurasi fonem, band pelafalan, atau kelancaran akustik yang ditebak.")}</Notice>{error&&<Notice tone="error">{error}</Notice>}<Panel title={text(lang,"Your practice sentence","Kalimat latihanmu")}><div className="learn-quote"><Icon name="speaking" size={30}/><p>{target}</p></div><div className="aru-actions"><Button secondary onClick={()=>{if(!window.speechSynthesis){setError("Speech playback is unavailable");return;}window.speechSynthesis.cancel();const u=new SpeechSynthesisUtterance(target);u.lang="en-GB";window.speechSynthesis.speak(u);}}>{text(lang,"Hear an example","Dengarkan contoh")}</Button><Button secondary busy={busy} onClick={()=>void sentence()}>{text(lang,"New sentence","Kalimat baru")}</Button></div></Panel><Panel title={text(lang,"Try it in your own voice","Coba dengan suaramu")}><Recorder lang={lang} onTranscript={t=>setTranscript(t)} disabled={busy}/><label className="learn-field"><span>{text(lang,"What was recognized · editable","Kata yang dikenali · dapat diedit")}</span><textarea rows={4} value={transcript} maxLength={2400} onChange={e=>setTranscript(e.target.value)}/></label><Button busy={busy} disabled={!transcript.trim()} onClick={()=>void review()}>{text(lang,"Get word-level guidance","Dapatkan panduan kata")}</Button></Panel>{feedback&&<Panel title={text(lang,"Guidance for your next attempt","Panduan untuk percobaan berikutnya")}>{feedback.stub&&<Notice>{text(lang,"Fixed demo feedback—not an assessment.","Umpan balik demo tetap, bukan penilaian.")}</Notice>}<p>{feedback.summary}</p><div className="learn-vocab-upgrades">{feedback.wordTips.map((v,i)=><div key={i}><b>{v.word}</b><p>{v.tip}</p></div>)}</div><p className="learn-fineprint">{text(lang,"General speaking tips are not findings about your actual stress or intonation.","Tips berbicara umum bukan temuan tentang tekanan kata atau intonasimu yang sebenarnya.")}</p></Panel>}</div>;
}
