import {useEffect,useRef,useState} from "react";
import {transcribe} from "./api";
import {Button,Notice,text,type Locale} from "./shared";
import {Icon} from "../views";
export function Recorder({lang,onTranscript,disabled=false}:{lang:Locale;onTranscript:(t:string,id?:string)=>void;disabled?:boolean}){
 const [state,setState]=useState<"idle"|"requesting"|"recording"|"transcribing">("idle"),[error,setError]=useState(""),[seconds,setSeconds]=useState(0);
 const media=useRef<MediaRecorder|null>(null),stream=useRef<MediaStream|null>(null),chunks=useRef<Blob[]>([]),alive=useRef(true),controller=useRef<AbortController|null>(null),started=useRef(0),pending=useRef(false);
 const stopTracks=()=>{stream.current?.getTracks().forEach(t=>t.stop());stream.current=null;};
 useEffect(()=>{alive.current=true;return()=>{alive.current=false;controller.current?.abort();if(media.current?.state==="recording")media.current.stop();stopTracks();};},[]);
 useEffect(()=>{if(state!=="recording")return;const id=setInterval(()=>{const elapsed=Math.floor((Date.now()-started.current)/1000);setSeconds(elapsed);if(elapsed>=300&&media.current?.state==="recording")media.current.stop();},500);return()=>clearInterval(id);},[state]);
 async function start(){if(pending.current||state!=="idle")return;setError("");if(!navigator.mediaDevices?.getUserMedia||!window.MediaRecorder){setError(text(lang,"Recording is unavailable. Use a secure browser connection or type your response.","Perekaman tidak tersedia. Gunakan koneksi browser aman atau ketik responsmu."));return;}
  pending.current=true;setState("requesting");try{const s=await navigator.mediaDevices.getUserMedia({audio:true});if(!alive.current){s.getTracks().forEach(t=>t.stop());return;}stream.current=s;const mime=["audio/webm;codecs=opus","audio/webm","audio/mp4"].find(m=>MediaRecorder.isTypeSupported(m));const rec=new MediaRecorder(s,mime?{mimeType:mime}:undefined);media.current=rec;chunks.current=[];started.current=Date.now();setSeconds(0);
   rec.ondataavailable=e=>{if(e.data.size)chunks.current.push(e.data);};
   rec.onstop=()=>{stopTracks();if(!alive.current)return;setState("transcribing");const blob=new Blob(chunks.current,{type:rec.mimeType});controller.current=new AbortController();transcribe(blob,controller.current.signal).then(out=>{if(alive.current){if(!out.transcript.trim())setError(text(lang,"No speech was recognized. Try again or type your response.","Tidak ada ucapan yang dikenali. Coba lagi atau ketik responsmu."));else onTranscript(out.transcript,out.jobId);}}).catch(e=>{if(alive.current)setError(e instanceof Error?e.message:"Transcription failed");}).finally(()=>{if(alive.current)setState("idle");});};
   rec.start();setState("recording");
  }catch{stopTracks();setError(text(lang,"Microphone access was denied or unavailable.","Akses mikrofon ditolak atau tidak tersedia."));if(alive.current)setState("idle");}finally{pending.current=false;}}
 return <div className="learn-recorder"><div className="learn-player"><span className={`learn-icon learn-speaking ${state==="recording"?"is-recording":""}`}><Icon name="speaking" size={24}/></span><div><b>{state==="recording"?`${text(lang,"Recording","Merekam")} · ${Math.floor(seconds/60)}:${String(seconds%60).padStart(2,"0")}`:state==="requesting"?text(lang,"Allow microphone access…","Izinkan akses mikrofon…"):state==="transcribing"?text(lang,"Transcribing your recording…","Mentranskripsikan rekamanmu…"):text(lang,"Use your voice","Gunakan suaramu")}</b><p>{text(lang,"Maximum 5 minutes · editable transcript","Maksimal 5 menit · transkrip dapat diedit")}</p></div><Button secondary busy={state==="transcribing"||state==="requesting"} disabled={disabled} onClick={()=>{if(state==="recording")media.current?.stop();else void start();}}>{state==="recording"?text(lang,"Stop recording","Hentikan rekaman"):text(lang,"Record","Rekam")}</Button></div><p className="learn-fineprint">{text(lang,"Recording is uploaded to this app for transcription. Audio alone does not enable calibrated pronunciation scoring.","Rekaman diunggah ke aplikasi ini untuk transkripsi. Audio saja tidak mengaktifkan penilaian pelafalan terkalibrasi.")}</p>{error&&<Notice tone="error">{error}</Notice>}</div>;
}
