import {useState} from "react";
import {AvatarEditor,CheckpointsEditor} from "./ManageExtras";
import {request} from "./api";
import {Heading,Panel,Notice,Button,Dialog,LoadState,useLoad,text,type Locale,type Nav} from "./shared";
import {getTheme,getFont,setTheme,setFont,type Font,type Theme} from "../../lib/settings";
import {Icon} from "../views";
interface Profile{id:number;name:string;email:string|null;emailVerified:boolean;isAdmin?:boolean;hasPassword?:boolean;targetBand:number;skillTargets?:Record<string,number|string>;country?:string;examDate?:string;bio?:string;reminderTime?:string;reminderTz?:string;avatar?:string}
interface Device{device:string;current:boolean;lastSeenAt:string;createdAt:string}
export function SettingsScreen({lang,nav}:{lang:Locale;nav:Nav}){
 const p=useLoad(()=>request<Profile>("/api/account/me"),"settings"),[tab,setTab]=useState("profile");
 const sections=[{id:"profile",label:text(lang,"Profile","Profil"),icon:"user"},{id:"targets",label:text(lang,"Learning targets","Target belajar"),icon:"target"},{id:"checkpoints",label:text(lang,"Planned checkpoints","Checkpoint rencana"),icon:"journey"},{id:"security",label:text(lang,"Security","Keamanan"),icon:"shield"},{id:"devices",label:text(lang,"Devices & sessions","Perangkat & sesi"),icon:"globe"},{id:"reminders",label:text(lang,"Reminders","Pengingat"),icon:"calendar"},{id:"accessibility",label:text(lang,"Appearance & reading","Tampilan & membaca"),icon:"book"},{id:"data",label:text(lang,"Your data","Datamu"),icon:"layers"},...(p.data?.isAdmin?[{id:"admin",label:text(lang,"Administration","Administrasi"),icon:"settings"}]:[])];
 return <div className="learn-page"><Heading title={text(lang,"Make this space yours","Atur ruang belajarmu")} description={text(lang,"Your learning preferences, account security, and data controls.","Preferensi belajar, keamanan akun, dan kontrol datamu.")} icon="settings" tag="ACCOUNT SETTINGS" nav={nav} lang={lang}/>{p.busy||p.error?<LoadState busy={p.busy} error={p.error} onRetry={p.retry} lang={lang}/>:p.data&&<div className="learn-settings-layout"><nav className="learn-settings-nav" aria-label="Account settings">{sections.map(s=><button key={s.id} aria-current={tab===s.id?"page":undefined} onClick={()=>setTab(s.id)}><Icon name={s.icon} size={19}/>{s.label}</button>)}</nav><div className="learn-stack">{tab==="profile"?<ProfileForm key={p.data.id} user={p.data} lang={lang} onSave={p.setData}/>:tab==="targets"?<TargetForm user={p.data} lang={lang} onSave={p.setData}/>:tab==="checkpoints"?<CheckpointsEditor lang={lang}/>:tab==="security"?<SecurityForm user={p.data} lang={lang}/>:tab==="devices"?<DeviceList lang={lang} nav={nav}/>:tab==="reminders"?<ReminderForm user={p.data} lang={lang} onSave={p.setData}/>:tab==="accessibility"?<Appearance lang={lang}/>:tab==="data"?<DataControls lang={lang} nav={nav}/>:<AdminControls lang={lang} userId={p.data.id}/>}</div></div>}</div>;
}
function ProfileForm({user,lang,onSave}:{user:Profile;lang:Locale;onSave:(u:Profile)=>void}){
 const [name,setName]=useState(user.name),[country,setCountry]=useState(user.country||""),[date,setDate]=useState(user.examDate||""),[bio,setBio]=useState(user.bio||""),[busy,setBusy]=useState(false),[error,setError]=useState(""),[saved,setSaved]=useState(false),[verification,setVerification]=useState("");
 async function save(){setBusy(true);setError("");setSaved(false);try{const u=await request<Profile>("/api/account/profile",{name,country,examDate:date,bio},"PATCH");onSave(u);setSaved(true);}catch(e){setError(e instanceof Error?e.message:"Profile was not saved");}finally{setBusy(false);}}
 async function resend(){setBusy(true);setError("");try{await request("/api/account/verify/resend",{});setVerification(text(lang,"Verification requested. Delivery depends on the configured email service.","Verifikasi diminta. Pengiriman bergantung pada layanan email yang dikonfigurasi."));}catch(e){setError(e instanceof Error?e.message:"Verification request failed");}finally{setBusy(false);}}
 return <><Panel title={text(lang,"Profile details","Detail profil")}><div className="learn-profile-card"><div className="learn-avatar">{user.avatar?<img src={user.avatar} alt="Profile"/>:user.name.slice(0,1)||"A"}</div><div><h3>{user.name||text(lang,"Your profile","Profilmu")}</h3><p>{user.email||text(lang,"No email attached","Belum ada email")}</p><span className="learn-tag">{user.emailVerified?text(lang,"Email verified","Email terverifikasi"):text(lang,"Email not verified","Email belum terverifikasi")}</span></div></div><AvatarEditor lang={lang} onUpdated={avatar=>onSave({...user,avatar})}/><div className="learn-form-grid"><label className="learn-field"><span>{text(lang,"Display name","Nama tampilan")}</span><input value={name} maxLength={120} onChange={e=>{setName(e.target.value);setSaved(false);}}/></label><label className="learn-field"><span>{text(lang,"Country","Negara")}</span><input value={country} maxLength={80} onChange={e=>setCountry(e.target.value)}/></label><label className="learn-field"><span>{text(lang,"Target exam date · optional","Tanggal ujian target · opsional")}</span><input type="date" value={date} onChange={e=>setDate(e.target.value)}/></label></div><label className="learn-field"><span>{text(lang,"Learning notes","Catatan belajar")}</span><textarea rows={3} maxLength={2000} value={bio} onChange={e=>setBio(e.target.value)}/></label><Button busy={busy} disabled={!name.trim()} onClick={()=>void save()}>{text(lang,"Save profile","Simpan profil")}</Button>{saved&&<Notice tone="success">{text(lang,"Profile saved.","Profil tersimpan.")}</Notice>}{error&&<Notice tone="error">{error}</Notice>}</Panel>{!user.emailVerified&&<Panel title={text(lang,"Verify your email","Verifikasi emailmu")}><p>{text(lang,"Verify email ownership to use features that require it. Verification never grants admin rights by itself.","Verifikasi kepemilikan email untuk menggunakan fitur yang memerlukannya. Verifikasi saja tidak memberikan hak admin.")}</p><Button secondary busy={busy} onClick={()=>void resend()}>{text(lang,"Request verification email","Minta email verifikasi")}</Button>{verification&&<Notice>{verification}</Notice>}</Panel>}</>;
}
function TargetForm({user,lang,onSave}:{user:Profile;lang:Locale;onSave:(u:Profile)=>void}){
 const [overall,setOverall]=useState(user.targetBand),[targets,setTargets]=useState<Record<string,string>>(()=>Object.fromEntries(Object.entries(user.skillTargets||{}).map(([k,v])=>[k,typeof v==="number"?String(v):""]))),[busy,setBusy]=useState(false),[message,setMessage]=useState(""),[error,setError]=useState("");const bands=Array.from({length:11},(_,i)=>4+i/2);
 async function save(){setBusy(true);setError("");setMessage("");try{const numeric=Object.fromEntries(Object.entries(targets).filter(([,v])=>v!=="").map(([k,v])=>[k,Number(v)]));onSave(await request<Profile>("/api/account/profile",{targetBand:overall,skillTargets:numeric},"PATCH"));setMessage(text(lang,"Numeric targets saved.","Target numerik tersimpan."));}catch(e){setError(e instanceof Error?e.message:"Targets were not saved");}finally{setBusy(false);}}
 return <Panel title={text(lang,"Set requirements you have checked","Tetapkan syarat yang sudah diperiksa")}><Notice>{text(lang,"ARUORA does not infer a university, scholarship, or employer requirement. Enter verified targets yourself.","ARUORA tidak menebak syarat universitas, beasiswa, atau perusahaan. Masukkan target yang telah kamu verifikasi.")}</Notice><label className="learn-field"><span>{text(lang,"Overall IELTS target","Target overall IELTS")}</span><select value={overall} onChange={e=>setOverall(Number(e.target.value))}>{bands.map(v=><option key={v} value={v}>{v.toFixed(1)}</option>)}</select></label><div className="learn-form-grid">{["listening","reading","writing","speaking"].map(s=><label key={s} className="learn-field"><span>{s[0].toUpperCase()+s.slice(1)}</span><select value={targets[s]||""} onChange={e=>setTargets(t=>({...t,[s]:e.target.value}))}><option value="">{text(lang,"Use overall target","Gunakan target overall")}</option>{bands.map(v=><option key={v} value={v}>{v.toFixed(1)}</option>)}</select></label>)}</div><p className="learn-fineprint">{text(lang,"Older CEFR-text targets are not silently converted into numeric band requirements.","Target lama berupa teks CEFR tidak diubah diam-diam menjadi persyaratan band numerik.")}</p><Button busy={busy} onClick={()=>void save()}>{text(lang,"Save targets","Simpan target")}</Button>{message&&<Notice tone="success">{message}</Notice>}{error&&<Notice tone="error">{error}</Notice>}</Panel>;
}
function SecurityForm({user,lang}:{user:Profile;lang:Locale}){
 const [current,setCurrent]=useState(""),[next,setNext]=useState(""),[confirm,setConfirm]=useState(""),[busy,setBusy]=useState(false),[message,setMessage]=useState(""),[error,setError]=useState("");
 async function save(){setBusy(true);setError("");setMessage("");try{await request("/api/account/password",{currentPassword:current,newPassword:next});setCurrent("");setNext("");setConfirm("");setMessage(text(lang,"Password changed. Other sessions were revoked.","Kata sandi diubah. Sesi lain telah dicabut."));}catch(e){setError(e instanceof Error?e.message:"Password was not changed");}finally{setBusy(false);}}
 return <Panel title={text(lang,"Password & account security","Kata sandi & keamanan akun")}><Notice>{text(lang,"Use a unique passphrase of at least 15 characters. Do not reuse credentials from another service.","Gunakan frasa sandi unik minimal 15 karakter. Jangan gunakan ulang kredensial layanan lain.")}</Notice>{user.hasPassword!==false&&<label className="learn-field"><span>{text(lang,"Current password","Kata sandi saat ini")}</span><input type="password" autoComplete="current-password" value={current} onChange={e=>setCurrent(e.target.value)}/></label>}<label className="learn-field"><span>{text(lang,"New password","Kata sandi baru")}</span><input type="password" autoComplete="new-password" value={next} onChange={e=>setNext(e.target.value)} minLength={15}/></label><label className="learn-field"><span>{text(lang,"Confirm new password","Konfirmasi kata sandi baru")}</span><input type="password" autoComplete="new-password" value={confirm} onChange={e=>setConfirm(e.target.value)}/></label><Button busy={busy} disabled={next.length<15||next!==confirm||(user.hasPassword!==false&&!current)} onClick={()=>void save()}>{text(lang,"Update password","Perbarui kata sandi")}</Button>{message&&<Notice tone="success">{message}</Notice>}{error&&<Notice tone="error">{error}</Notice>}</Panel>;
}
function DeviceList({lang,nav}:{lang:Locale;nav:Nav}){
 const r=useLoad(()=>request<Device[]>("/api/account/sessions"),"devices"),[busy,setBusy]=useState(false),[error,setError]=useState(""),[confirm,setConfirm]=useState<"others"|"all"|null>(null);
 async function revoke(){setBusy(true);setError("");try{await request(`/api/account/sessions${confirm==="others"?"/others":""}`,undefined,"DELETE");if(confirm==="all"){window.dispatchEvent(new CustomEvent("ielts:session-expired"));nav("/login");}else r.retry();setConfirm(null);}catch(e){setError(e instanceof Error?e.message:"Revocation was not confirmed");}finally{setBusy(false);}}
 return r.busy||r.error?<LoadState busy={r.busy} error={r.error} onRetry={r.retry} lang={lang}/>:<Panel title={text(lang,"Devices & active sessions","Perangkat & sesi aktif")}><p>{text(lang,"These sessions are returned by the server. Revocation is confirmed before this list refreshes.","Sesi berikut berasal dari server. Pencabutan dikonfirmasi sebelum daftar diperbarui.")}</p><div className="learn-device-list">{r.data?.map((d,i)=><article key={i}><Icon name="globe" size={26}/><div><h3>{/Windows/i.test(d.device)?"Windows browser":/Android/i.test(d.device)?"Android browser":/iPhone|iPad/i.test(d.device)?"iOS browser":"Browser session"}</h3><p>{text(lang,"Last active","Terakhir aktif")}: {d.lastSeenAt?new Date(d.lastSeenAt).toLocaleString():"—"}</p></div>{d.current&&<span className="learn-tag">{text(lang,"This device","Perangkat ini")}</span>}</article>)}</div><div className="aru-actions"><Button secondary onClick={()=>setConfirm("others")} disabled={(r.data?.length||0)<2}>{text(lang,"Sign out other devices","Keluarkan perangkat lain")}</Button><Button secondary onClick={()=>setConfirm("all")}>{text(lang,"Sign out all devices","Keluarkan semua perangkat")}</Button></div>{error&&<Notice tone="error">{error}</Notice>}{confirm&&<Dialog title={text(lang,"Confirm session revocation","Konfirmasi pencabutan sesi")} onClose={()=>setConfirm(null)}><p>{confirm==="all"?text(lang,"This includes your current device.","Ini termasuk perangkatmu saat ini."):text(lang,"Your current session will remain active.","Sesimu saat ini tetap aktif.")}</p><div className="aru-actions"><Button secondary onClick={()=>setConfirm(null)}>{text(lang,"Cancel","Batal")}</Button><Button busy={busy} onClick={()=>void revoke()}>{text(lang,"Confirm sign-out","Konfirmasi keluar")}</Button></div></Dialog>}</Panel>;
}
function ReminderForm({user,lang,onSave}:{user:Profile;lang:Locale;onSave:(u:Profile)=>void}){
 const [enabled,setEnabled]=useState(!!user.reminderTime),[time,setTime]=useState(user.reminderTime||"19:00"),[zone,setZone]=useState(user.reminderTz||Intl.DateTimeFormat().resolvedOptions().timeZone||"UTC"),[busy,setBusy]=useState(false),[error,setError]=useState(""),[saved,setSaved]=useState(false);
 async function save(){setBusy(true);setError("");setSaved(false);try{onSave(await request<Profile>("/api/account/profile",{reminderTime:enabled?time:null,reminderTz:enabled?zone:null},"PATCH"));setSaved(true);}catch(e){setError(e instanceof Error?e.message:"Reminder not saved");}finally{setBusy(false);}}
 return <Panel title={text(lang,"A reminder on your terms","Pengingat sesuai ritmemu")}><label className="learn-toggle"><span>{text(lang,"Daily study reminder","Pengingat belajar harian")}</span><input type="checkbox" checked={enabled} onChange={e=>setEnabled(e.target.checked)}/></label><div className="learn-form-grid"><label className="learn-field"><span>{text(lang,"Local reminder hour","Jam pengingat lokal")}</span><select disabled={!enabled} value={time} onChange={e=>setTime(e.target.value)}>{Array.from({length:24},(_,h)=>`${String(h).padStart(2,"0")}:00`).map(t=><option key={t}>{t}</option>)}</select></label><label className="learn-field"><span>{text(lang,"Time zone (IANA)","Zona waktu (IANA)")}</span><input disabled={!enabled} value={zone} maxLength={64} onChange={e=>setZone(e.target.value)} placeholder="Asia/Jakarta"/></label></div><Notice>{text(lang,"Email delivery requires configured SMTP and scheduled reminder jobs. Saving a preference is not proof that an email was delivered.","Pengiriman email memerlukan SMTP dan penjadwalan reminder. Preferensi tersimpan bukan bukti bahwa email terkirim.")}</Notice><Button busy={busy} onClick={()=>void save()}>{text(lang,"Save reminder","Simpan pengingat")}</Button>{saved&&<Notice tone="success">{text(lang,"Reminder preference saved.","Preferensi pengingat tersimpan.")}</Notice>}{error&&<Notice tone="error">{error}</Notice>}</Panel>;
}
function Appearance({lang}:{lang:Locale}){
 const [theme,updateTheme]=useState<Theme>(getTheme()),[font,updateFont]=useState<Font>(getFont());
 return <Panel title={text(lang,"A comfortable reading space","Ruang baca yang nyaman")}><label className="learn-field"><span>{text(lang,"Color theme","Tema warna")}</span><select value={theme} onChange={e=>{const v=e.target.value as Theme;updateTheme(v);setTheme(v);}}><option value="light">{text(lang,"Light","Terang")}</option><option value="dark">{text(lang,"Dark","Gelap")}</option></select></label><label className="learn-field"><span>{text(lang,"Reading font preference","Preferensi font membaca")}</span><select value={font} onChange={e=>{const v=e.target.value as Font;updateFont(v);setFont(v);}}><option value="default">{text(lang,"Default","Bawaan")}</option><option value="hyperlegible">Atkinson Hyperlegible</option><option value="dyslexic">OpenDyslexic</option></select></label><div className="learn-reading-sample"><span className="learn-eyebrow">{text(lang,"READING PREVIEW","PRATINJAU BACAAN")}</span><h2>Small steps. Clear direction.</h2><p>Learning grows through practice, reflection, and a next step that you can understand.</p></div><Notice>{text(lang,"Motion follows your operating system's reduced-motion setting. Font choices are preferences, not a clinical accessibility guarantee.","Gerakan mengikuti pengaturan reduced motion sistem operasi. Pilihan font merupakan preferensi, bukan jaminan aksesibilitas klinis.")}</Notice></Panel>;
}
function DataControls({lang,nav}:{lang:Locale;nav:Nav}){
 const [busy,setBusy]=useState(false),[error,setError]=useState(""),[confirm,setConfirm]=useState(false),[typed,setTyped]=useState("");
 async function exportData(){setBusy(true);setError("");try{const d=await request("/api/account/export");const u=URL.createObjectURL(new Blob([JSON.stringify(d,null,2)],{type:"application/json"}));const a=document.createElement("a");a.href=u;a.download="aruora-account-export.json";document.body.append(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(u),1000);}catch(e){setError(e instanceof Error?e.message:"Export failed");}finally{setBusy(false);}}
 async function remove(){setBusy(true);setError("");try{await request("/api/account",undefined,"DELETE");setConfirm(false);window.dispatchEvent(new CustomEvent("ielts:session-expired"));nav("/");}catch(e){setError(e instanceof Error?e.message:"Account deletion was not confirmed");}finally{setBusy(false);}}
 return <><Panel title={text(lang,"A copy of your learning data","Salinan data belajarmu")}><p>{text(lang,"Export your profile, submitted work, cards, and related account data. Open practice answer keys are not included.","Ekspor profil, hasil yang dikirim, kartu, dan data terkait akun. Kunci jawaban latihan yang masih terbuka tidak disertakan.")}</p><Button secondary busy={busy} onClick={()=>void exportData()}>{text(lang,"Export my data","Ekspor dataku")}<Icon name="layers" size={17}/></Button></Panel><Panel title={text(lang,"Delete this account","Hapus akun ini")} className="learn-danger-panel"><p>{text(lang,"Permanently remove your account and owned learning records. Security and financial audit retention may follow separate policies.","Hapus permanen akun dan catatan belajar milikmu. Retensi audit keamanan dan keuangan dapat mengikuti kebijakan terpisah.")}</p><button className="learn-danger-button" onClick={()=>setConfirm(true)}>{text(lang,"Delete account","Hapus akun")}</button></Panel>{error&&<Notice tone="error">{error}</Notice>}{confirm&&<Dialog title={text(lang,"Delete your account permanently?","Hapus akunmu secara permanen?")} onClose={()=>{if(!busy)setConfirm(false);}}>{error&&<Notice tone="error">{error}</Notice>}<Notice>{text(lang,"This cannot be undone. Export a copy first if you need one.","Tindakan ini tidak dapat dibatalkan. Ekspor salinan terlebih dahulu bila diperlukan.")}</Notice><label className="learn-field"><span>{text(lang,"Type DELETE to confirm","Ketik DELETE untuk konfirmasi")}</span><input value={typed} onChange={e=>setTyped(e.target.value)} autoComplete="off"/></label><div className="aru-actions"><Button secondary onClick={()=>setConfirm(false)}>{text(lang,"Keep my account","Pertahankan akun")}</Button><button disabled={typed!=="DELETE"||busy} className="learn-danger-button" onClick={()=>void remove()}>{text(lang,"Permanently delete","Hapus permanen")}</button></div></Dialog>}</>;
}
function AdminControls({lang,userId}:{lang:Locale;userId:number}){
 const r=useLoad(()=>request<{id:number;email:string;name:string;attempts:number}[]>("/api/admin/users"),"admin"),[password,setPassword]=useState(""),[totp,setTotp]=useState(""),[busy,setBusy]=useState(false),[error,setError]=useState(""),[selected,setSelected]=useState<{id:number;action:"delete"|"reset"}|null>(null);
 async function action(){if(!selected)return;setBusy(true);setError("");try{await request("/api/admin/reauth",{password,totp});setPassword("");setTotp("");await request(`/api/admin/users/${selected.id}${selected.action==="reset"?"/reset-password":""}`,selected.action==="reset"?{}:undefined,selected.action==="reset"?"POST":"DELETE");setSelected(null);r.retry();}catch(e){setError(e instanceof Error?e.message:"Admin action failed");}finally{setBusy(false);setPassword("");setTotp("");}}
 return <><Notice>{text(lang,"Admin access requires verified identity, the server allow-list, and configured MFA. Destructive actions also require fresh reauthentication.","Akses admin memerlukan identitas terverifikasi, allow-list server, dan MFA yang dikonfigurasi. Tindakan destruktif juga memerlukan autentikasi ulang.")}</Notice>{r.busy||r.error?<LoadState busy={r.busy} error={r.error} onRetry={r.retry} lang={lang}/>:<Panel title={text(lang,"Account administration","Administrasi akun")}><div className="learn-table-wrap"><table className="learn-table"><thead><tr><th>{text(lang,"Account","Akun")}</th><th>{text(lang,"Attempts","Latihan")}</th><th>{text(lang,"Actions","Tindakan")}</th></tr></thead><tbody>{r.data?.map(u=><tr key={u.id}><td><b>{u.name||u.email}</b><small>{u.email}</small></td><td>{u.attempts}</td><td>{u.id===userId?<span className="learn-tag">{text(lang,"Your account","Akunmu")}</span>:<div className="aru-actions"><button className="aru-text-button" onClick={()=>setSelected({id:u.id,action:"reset"})}>{text(lang,"Reset password","Reset sandi")}</button><button className="aru-text-button" onClick={()=>setSelected({id:u.id,action:"delete"})}>{text(lang,"Delete","Hapus")}</button></div>}</td></tr>)}</tbody></table></div></Panel>}{error&&<Notice tone="error">{error}</Notice>}{selected&&<Dialog title={text(lang,"Reauthenticate this admin action","Autentikasi ulang tindakan admin")} onClose={()=>{if(!busy)setSelected(null);}}>{error&&<Notice tone="error">{error}</Notice>}<p>{selected.action==="delete"?text(lang,"This permanently deletes the selected user's account and owned records.","Ini menghapus permanen akun dan catatan milik pengguna yang dipilih."):text(lang,"Request a reset email and revoke the selected user's active sessions.","Minta email reset dan cabut sesi aktif pengguna yang dipilih.")}</p><label className="learn-field"><span>{text(lang,"Your admin password","Kata sandi adminmu")}</span><input type="password" autoComplete="current-password" value={password} onChange={e=>setPassword(e.target.value)}/></label><label className="learn-field"><span>{text(lang,"MFA code · when configured","Kode MFA · bila dikonfigurasi")}</span><input inputMode="numeric" autoComplete="one-time-code" maxLength={6} value={totp} onChange={e=>setTotp(e.target.value.replace(/\D/g,""))}/></label><div className="aru-actions"><Button secondary onClick={()=>setSelected(null)}>{text(lang,"Cancel","Batal")}</Button><Button busy={busy} disabled={!password} onClick={()=>void action()}>{text(lang,"Confirm action","Konfirmasi tindakan")}</Button></div></Dialog>}</>;
}
