import React,{useState} from "react";
import {api} from "../lib/api/client";
import {useT} from "../lib/i18n";
import {Icon} from "./views";
export function ForgotForm({onBack}:{onBack:()=>void}){
 const {lang}=useT(),c=(en:string,id:string)=>lang==="id"?id:en;
 const [email,setEmail]=useState(""),[sent,setSent]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState("");
 async function submit(e:React.FormEvent){e.preventDefault();if(busy)return;setBusy(true);setError("");try{await api.accountForgot(email.trim());setSent(true);}catch{setError(c("The request did not complete. Please try again later.","Permintaan belum berhasil. Silakan coba lagi nanti."));}finally{setBusy(false);}}
 return <form className="aru-auth-form" onSubmit={submit}><div><span className="aru-eyebrow">{c("BACK TO YOUR JOURNEY","KEMBALI KE PERJALANANMU")}</span><h1>{c("Reset your password.","Atur ulang kata sandi.")}</h1><p>{sent?c("If this address belongs to an account and email delivery is available, a reset link has been requested. Check your inbox and spam folder.","Jika alamat ini terdaftar dan pengiriman email tersedia, tautan reset telah diminta. Periksa kotak masuk dan folder spam."):c("Enter your email to request a reset link.","Masukkan email untuk meminta tautan reset.")}</p></div>{!sent&&<label className="aru-field"><span>Email</span><input type="email" required autoComplete="email" value={email} onChange={e=>setEmail(e.target.value)}/></label>}{error&&<p role="alert" className="aru-form-error">{error}</p>}{!sent&&<button type="submit" className="aru-button" disabled={busy}>{busy?c("Requesting…","Meminta…"):c("Request reset link","Minta tautan reset")}<Icon name="arrow" size={17}/></button>}<button className="aru-text-button aru-auth-switch" type="button" onClick={onBack}>{c("Back to log in","Kembali masuk")}</button></form>;
}
export interface OneTimeLink {kind:"verify"|"reset";token:string}
export function RecoveryForm({link,onDone}:{link:OneTimeLink;onDone:()=>void}){
 const {lang}=useT(),c=(en:string,id:string)=>lang==="id"?id:en;
 const [busy,setBusy]=useState(false),[done,setDone]=useState(false),[error,setError]=useState(""),[password,setPassword]=useState("");
 const reset=link.kind==="reset";
 async function submit(e:React.FormEvent){e.preventDefault();if(busy)return;setBusy(true);setError("");try{if(reset)await api.accountReset({token:link.token,newPassword:password});else await api.accountVerify(link.token);setPassword("");setDone(true);}catch{setError(c("This link could not be completed. It may have expired or already been used. Try again, or request a new message.","Tautan ini belum dapat diproses. Mungkin kedaluwarsa atau sudah digunakan. Coba lagi atau minta pesan baru."));}finally{setBusy(false);}}
 return <form className="aru-auth-form" onSubmit={submit}><div><span className="aru-eyebrow">{c("ACCOUNT SECURITY","KEAMANAN AKUN")}</span><h1>{done?c("All set.","Selesai."):reset?c("Choose a new password.","Pilih kata sandi baru."):c("Confirm your email.","Konfirmasi emailmu.")}</h1><p>{done?reset?c("Your password was changed. Log in again with the new password.","Kata sandimu telah diubah. Masuk kembali dengan kata sandi baru."):c("Email ownership was verified. Continue to your account.","Kepemilikan email telah diverifikasi. Lanjutkan ke akunmu."):c("Confirm this action to continue. The one-time token is not stored in the browser.","Konfirmasi tindakan ini untuk melanjutkan. Token sekali pakai tidak disimpan di browser.")}</p></div>{reset&&!done&&<label className="aru-field"><span>{c("New password","Kata sandi baru")}</span><input type="password" autoComplete="new-password" required minLength={15} value={password} onChange={e=>setPassword(e.target.value)}/><small>{c("Use at least 15 characters.","Gunakan minimal 15 karakter.")}</small></label>}{error&&<p className="aru-form-error" role="alert">{error}</p>}{done?<button type="button" onClick={onDone} className="aru-button">{c("Continue to log in","Lanjut masuk")}<Icon name="arrow" size={17}/></button>:<button type="submit" disabled={busy} className="aru-button">{busy?c("Working…","Memproses…"):reset?c("Save new password","Simpan kata sandi baru"):c("Verify my email","Verifikasi emailku")}<Icon name="arrow" size={17}/></button>}</form>;
}
