"""add reminder_tz

Revision ID: 9413f2a93a7e
Revises: 8326c9605659
Create Date: 2026-07-01 15:18:16.180461

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9413f2a93a7e'
down_revision: Union[str, None] = '8326c9605659'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_profile', sa.Column('reminder_tz', sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_profile', 'reminder_tz')
    # ### end Alembic commands ###
